api/urls.py
from django.urls import path
from .views import PlaceApiView, PlaceDetailApiView, ReviewsApiView


app_name = 'api'

urlpatterns = [
    path('places-list/', PlaceApiView.as_view(), name="places"),
    path('place-detail/<int:id>/', PlaceDetailApiView.as_view(), name="place_detail"),


    path('reviews/', ReviewsApiView.as_view(), name="reviews"),

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .views import landing_page, HomeView
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name='landing_page'),
    path('home/', HomeView.as_view(), name='home'),
    path('users/', include('users.urls')),
    path('places/', include('places.urls')),
    path('api/', include('api.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

places/urls.py
from django.urls import path
from .views import PlaceListView, PlaceDetailView, AddCommentView

app_name = 'places'

urlpatterns = [
    path('list/', PlaceListView.as_view(), name="list"),
    path('detail/<int:pk>/', PlaceDetailView.as_view(), name="detail"),
    path('<int:id>/add_comment/', AddCommentView.as_view(), name="add_comment"),
]

places/models.py
from django.db import models
from django.utils import timezone
from users.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


class Place(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    address = models.CharField(max_length=255)
    image = models.ImageField(upload_to="place_images/", default="")

    def __str__(self):
        return self.name


class Owner(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class PlaceOwner(models.Model):
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.place.name} owned by {self.owner}"


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    place = models.ForeignKey(Place, on_delete=models.CASCADE, related_name="izohlar")
    comment_text = models.TextField()
    stars_given = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateField(default=timezone.now)

    def __str__(self):
        return f"{self.user} commented to {self.place.name} and gave {self.stars_given} stars"

places/forms.py
from django import forms
from .models import Comment


class PlaceCommentForm(forms.ModelForm):
    stars_given = forms.IntegerField(max_value=5, min_value=1)
    comment_text = forms.CharField(widget=forms.Textarea(attrs={"rows": 4}))

    class Meta:
        model = Comment
        fields = ('comment_text', 'stars_given')

places/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from .models import Place, Comment
from .forms import PlaceCommentForm


class PlaceListView(View):
    def get(self, request):

        places = Place.objects.all()
        search_query = request.GET.get("q", "")

        if search_query:
            places = places.filter(name__icontains=search_query)

        return render(request, 'places/list.html', {"places": places, "search_query": search_query})


class PlaceDetailView(View):

    def get(self, request, pk):
        form = PlaceCommentForm()

        place = get_object_or_404(Place, pk=pk)

        return render(request, 'places/detail.html', {"place": place, "form": form})


class AddCommentView(LoginRequiredMixin,View):

    def post(self, request, id):
        place = Place.objects.get(id=id)
        form = PlaceCommentForm(request.POST)

        if form.is_valid():
            Comment.objects.create(
                user=request.user,
                place=place,
                comment_text=form.cleaned_data['comment_text'],
                stars_given=form.cleaned_data['stars_given']

            )

            return redirect(reverse("places:detail", kwargs={"pk": place.id}))

        return render(request, 'places/detail.html', {"place": place, "form": form})

places/templates/places/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block title %}
	Place detail
{% endblock %}

{% block content %}
    <h1>Place detail</h1>

    <h3>{{ place.name }}</h3>

    <p>{{ place.description }}</p>


    <div class="row mb-4">

        <div class="col-6">
            <form action="{% url 'places:add_comment' place.id %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}

                <button type="submit" class="btn btn-primary">Add Comment</button>
            </form>
        </div>

    </div>

    <h1>Reviews</h1>
    <hr>

    {% for izoh in place.izohlar.all %}
        <div class="row mt-2 mb-2">
            <div class="col-1 me-2">
                <img src="{{ izoh.user.photo.url }}" alt="User Photo"  style="height: 100px; width: 100px; border-radius: 50%" >
            </div>

            <div class="col-7">
                <b>{{ izoh.user.username }}</b> rated it {{ izoh.stars_given }} stars <i>{{ izoh.created_at }}</i>
                <p class="mt-2 font-monospace">
                    {{ izoh.comment_text }}
                </p>
            </div>
        </div>

    {% endfor %}



{% endblock %}

places/templates/places/list.html
{% extends 'base.html' %}

{% block title %}
	Place List
{% endblock %}

{% block content %}

    <div class="row mb-3 mt-4">
        <div class="col-4 ">
            <form action="" method="get" class="d-flex">
                <input type="text" class="form-control me-2 " placeholder="Search" name="q" value="{{ search_query }}">
                <button class="btn btn-success">Search</button>
            </form>
        </div>
    </div>


{% if places %}
	{% for place in places %}
		<div class="mt-4">
            <div class="row">

                <div class="col-2 mb-4">
                    <img src="{{ place.image.url }}" alt="Place Image" style="width: 200px; height: 200px">
                </div>
                <div class="col-6">

                    <p>
                        {{ place.description|truncatewords:15 }}
                    </p>
                    <a class="btn btn-outline-primary" href="{% url 'places:detail' place.id %}">Read More</a>
                </div>
            </div>
        </div>
	{% endfor %}

{% else %}

    <h1>Places not found</h1>

{% endif %} 



{% endblock %}