api/urls.py
from django.urls import path
from .views import PlaceApiView, PlaceDetailApiView, ReviewsApiView


app_name = 'api'

urlpatterns = [
    path('places-list/', PlaceApiView.as_view(), name="places"),
    path('place-detail/<int:id>/', PlaceDetailApiView.as_view(), name="place_detail"),


    path('reviews/', ReviewsApiView.as_view(), name="reviews"),

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .views import landing_page, HomeView
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name='landing_page'),
    path('home/', HomeView.as_view(), name='home'),
    path('users/', include('users.urls')),
    path('places/', include('places.urls')),
    path('api/', include('api.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import (RegisterView, LoginView, LogoutView, ProfileUpdateView, ProfileView,
                    UsersView, SendFriendRequestView, MyNetworksView, AcceptFriendRequestView, ResetPasswordView,
                    IgnoreFriendRequestView, DeleteFromFriendsView)

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('profile/', ProfileUpdateView.as_view(), name="profile"),
    path('profile_view/', ProfileView.as_view(), name="profile_view"),
    path('list/', UsersView.as_view(), name="list"),
    path('reset-password/', ResetPasswordView.as_view(), name="reset_password"),



    #users friend request logic
    path('send_request/<int:id>/', SendFriendRequestView.as_view(), name="send_request"),
    path('networks/', MyNetworksView.as_view(), name="my_networks"),
    path('accept-friend/<int:id>/', AcceptFriendRequestView.as_view(), name="accept_friend"),
    path('ignore-friend/<int:id>/', IgnoreFriendRequestView.as_view(), name="ignore_friend"),
    path('delete-friend/<int:id>/', DeleteFromFriendsView.as_view(), name="delete_friend"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    photo = models.ImageField(upload_to="user_photos/",null=True, default='user_photos/applesize.jpeg')
    phone_number = models.CharField(max_length=13, unique=True, null=True, blank=True)
    friends = models.ManyToManyField('users.User', blank=True)


class FriendRequest(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='from_user')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='to_user')
    is_accepted = models.BooleanField(default=False)


    def __str__(self):
        return f"{self.from_user.username} sent friend request to {self.to_user}"

    class Meta:
        unique_together = ['from_user', 'to_user']

users/forms.py
from .models import User
from django import forms


class RegisterForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['password_confirm'] = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def clean_password_confirm(self):
        password = self.cleaned_data['password']
        password_confirm = self.cleaned_data['password_confirm']

        if password_confirm != password:
            raise forms.ValidationError("Passwordlar bir biriga mos emas")

        return password

    def clean_username(self):
        username = self.cleaned_data['username']

        if len(username) < 5 or len(username) > 30:
            raise forms.ValidationError("username 5 va 30 orasida bo'lishi lozim")

        return username


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username']

        if len(username) < 5 or len(username) > 30:
            raise forms.ValidationError("username 5 va 30 orasida bo'lishi lozim")

        return username


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'photo', 'phone_number')



class ResetPasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput)
    new_password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)


    def clean(self):
        new_password = self.cleaned_data['new_password']
        confirm_password = self.cleaned_data['confirm_password']

        if new_password != confirm_password:
            raise forms.ValidationError("Passwordlar bir biriga mos emas")

        return self.cleaned_data

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from .forms import RegisterForm,LoginForm, ProfileUpdateForm, ResetPasswordForm
from .models import User, FriendRequest

class RegisterView(View):

    def get(self, request):

        form = RegisterForm()
        return render(request, 'users/register.html', context={'form': form})

    def post(self, request):
        form = RegisterForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect('landing_page')

        return render(request, 'users/register.html', context={'form': form})


class LoginView(View):
    def get(self, request):

        form = LoginForm()
        return render(request, 'users/login.html', context={'form': form})

    def post(self, request):
        form = LoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)

                messages.success(request,"Siz muvafaqiyatli Login qildingiz")

                return redirect('landing_page')

        return render(request, 'users/login.html', context={'form': form})


class LogoutView(LoginRequiredMixin,View):
    def get(self, request):

        logout(request)

        messages.success(request,"Siz muvafaqiyatli logout qildingiz")

        return redirect('landing_page')


class ProfileUpdateView(LoginRequiredMixin,View):

    def get(self, request):
        form = ProfileUpdateForm(instance=request.user)

        return render(request, 'users/profile.html', {"form": form})

    def post(self, request):

        form = ProfileUpdateForm(instance=request.user, data=request.POST, files=request.FILES)

        if form.is_valid():
            form.save()

            messages.info(request,"Profile update qilindi")

            return redirect('places:list')

        return render(request, 'users/profile.html', {"form": form})


class ProfileView(LoginRequiredMixin, View):
    def get(self, request):

        return render(request, 'users/profile_view.html')


class UsersView(LoginRequiredMixin, View):
    def get(self, request):
        users = User.objects.exclude(username=request.user.username).exclude(friends=request.user)

        friend_requests = User.objects.filter(id__in=FriendRequest.objects.filter(from_user=request.user).values_list('to_user'))



        return render(request, 'users/users_list.html', {"users": users, "friend_requests": friend_requests})


class MyNetworksView(LoginRequiredMixin, View):
    def get(self, request):
        networks = FriendRequest.objects.filter(to_user=request.user, is_accepted=False)

        return render(request, 'users/networks_list.html', {"networks": networks})


class AcceptFriendRequestView(LoginRequiredMixin, View):
    def get(self, request, id):
        friend_request = FriendRequest.objects.get(id=id)
        from_user = friend_request.from_user
        main_user = request.user

        main_user.friends.add(from_user)
        from_user.friends.add(main_user)

        friend_request.is_accepted = True
        friend_request.save()

        return redirect("users:my_networks")


class IgnoreFriendRequestView(LoginRequiredMixin, View):
    def get(self, request, id):
        friend_request = FriendRequest.objects.get(id=id)
        friend_request.delete()
        return redirect("users:my_networks")


class DeleteFromFriendsView(LoginRequiredMixin, View):
    def get(self, request, id):
        friend = User.objects.get(id=id)
        user = request.user
        user.friends.remove(friend)
        friend.friends.remove(user)

        return redirect("users:my_networks")


class SendFriendRequestView(LoginRequiredMixin, View):
    def get(self, request, id):
        to_user = User.objects.get(id=id)
        from_user = request.user

        FriendRequest.objects.get_or_create(from_user=from_user, to_user=to_user)

        return redirect("users:list")


class ResetPasswordView(LoginRequiredMixin,View):

    def get(self, request):
        form = ResetPasswordForm()

        return render(request, 'users/reset_password.html', {"form": form})

    def post(self, request):
        form = ResetPasswordForm(request.POST)
        user = request.user

        if form.is_valid():
            if check_parol(user, form.cleaned_data['old_password']):
                user.set_password(form.cleaned_data['confirm_password'])
                user.save()
                return redirect('users:profile_view')

            else:
                return render(request, 'users/reset_password.html', {"form": form})

        return render(request, 'users/reset_password.html', {"form": form})


def check_parol(user, password):
    return user.check_password(password)

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
	Login Page
{% endblock %}

{% block content %}
	<h1>Login Page</h1>

    <form method="post">
        {% csrf_token %}

        {{form|crispy}}


        <p>Siz ro'yhatdan o'tmaganmisiz? <a href="{% url 'users:register' %}">Ro'yhatdan o'tish</a></p>
        <button type="submit">Login</button>
    </form>
    

{% endblock %}

users/templates/users/networks_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
	My Networks Page
{% endblock %}

{% block content %}
	<h1>My Networks Page</h1>
    <hr>

    {% for network in networks %}
            <div class="row">

            <div class="col-1">
                <img src="{{ network.from_user.photo.url }}" alt="user photos" height="100px" width="100px" style="border-radius: 50%; margin-bottom: 10px;">
            </div>

            <div class="col-6">
                <p><b>{{ network.from_user.username }}</b></p>
                <p>{{ network.from_user.email }}</p>
            </div>
            <div class="col">
                <a href="{% url 'users:ignore_friend' network.id %}" class="btn btn-outline-secondary">Ignore</a>
                <a href="{% url 'users:accept_friend' network.id %}" class="btn btn-outline-primary">Accept</a>
            </div>
        </div>

    {% endfor %}




    	<h1>My Friends</h1>
    <hr>

    {% for friend in user.friends.all %}
            <div class="row">

            <div class="col-1">
                <img src="{{ friend.photo.url }}" alt="user photos" height="100px" width="100px" style="border-radius: 50%; margin-bottom: 10px;">
            </div>

            <div class="col-6">
                <p><b>{{ friend.username }}</b></p>
                <p>{{ friend.email }}</p>
            </div>
            <div class="col">
                <a href="{% url 'users:delete_friend' friend.id %}" class="btn btn-outline-danger">Delete</a>

            </div>
        </div>

    {% endfor %}




{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
	Profile Page
{% endblock %}

{% block content %}
	<div>
        <h1>Profile Page</h1>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{form|crispy}}

            <button type="submit">Update</button>
        </form>
    </div>
{% endblock %}

users/templates/users/profile_view.html
{% extends 'base.html' %}


{% block title %}
	Profile View Page
{% endblock %}

{% block content %}
	<h1>Profile View Page</h1>


    <div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
        <div class="card p-4">
            <div class=" image d-flex flex-column justify-content-center align-items-center">
                {% if user.photo %}
                	<img src="{{ user.photo.url }}" style="border-radius: 50% " height="100" width="100" />
                {% else %}
                    <img src="https://stock.adobe.com/uz/images/default-avatar-profile-icon-vector-social-media-user-image/346839683" style="border-radius: 50% " height="100" width="100" />
                {% endif %}


                <span class="name mt-3">{{ user.username }}</span>
                <span class="idd">{{ user.email }}</span>

                <div class="d-flex flex-row justify-content-center align-items-center gap-2">
                    <span class="idd1">{{ user.phone_number }}</span> <span><i class="fa fa-copy"></i></span>
                </div>
                <div class=" d-flex mt-2">
                    <a href="{% url 'users:profile' %}" class="btn btn-dark">Edit Profile</a>
                    <a href="{% url 'users:reset_password' %}" class="btn btn-dark">Reset Password</a>
                </div>


                <div class=" px-2 rounded mt-4 date "> <span class="join">Joined {{ user.date_joined|date:"M d, Y" }}</span>
                </div>
            </div>
        </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
	Register Page
{% endblock %}

{% block content %}
	<h1>Register Page</h1>

    <form method="post">
        {% csrf_token %}

        {{form|crispy}}

        <button type="submit">Register</button>
    </form>
{% endblock %}

users/templates/users/reset_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
	Reset password Page
{% endblock %}

{% block content %}
	<div>
        <h1>Reset password Page</h1>

        <form method="post">
            {% csrf_token %}

            {{form|crispy}}

            <button type="submit">Reset Password</button>
        </form>
    </div>
{% endblock %}

users/templates/users/users_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Users Page
{% endblock %}

{% block content %}
    <h1>Users Page</h1>

    {% for friend in users %}
        <div class="row">
            <div class="col-1">
                <img src="{{ friend.photo.url }}" alt="user photos" height="100px" width="100px" style="border-radius: 50%; margin-bottom: 10px;">
            </div>

            <div class="col-6">
                <p><b>{{ friend.username }}</b></p>
                <p>{{ friend.email }}</p>
            </div>

            <div class="col">

                {% if friend in friend_requests %}
                    <button class="btn btn-outline-primary" disabled>Sent</button>
                {% else %}
                    <a href="{% url 'users:send_request' friend.id %}" class="btn btn-outline-primary">Send Request</a>
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% endblock %}