api/urls.py
from django.urls import path
from .views import PlaceApiView, PlaceDetailApiView, ReviewsApiView


app_name = 'api'

urlpatterns = [
    path('places-list/', PlaceApiView.as_view(), name="places"),
    path('place-detail/<int:id>/', PlaceDetailApiView.as_view(), name="place_detail"),


    path('reviews/', ReviewsApiView.as_view(), name="reviews"),

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .views import landing_page, HomeView
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name='landing_page'),
    path('home/', HomeView.as_view(), name='home'),
    path('users/', include('users.urls')),
    path('places/', include('places.urls')),
    path('api/', include('api.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

places/urls.py
from django.urls import path
from .views import PlaceListView, PlaceDetailView, AddCommentView

app_name = 'places'

urlpatterns = [
    path('list/', PlaceListView.as_view(), name="list"),
    path('detail/<int:pk>/', PlaceDetailView.as_view(), name="detail"),
    path('<int:id>/add_comment/', AddCommentView.as_view(), name="add_comment"),
]

users/urls.py
from django.urls import path
from .views import (RegisterView, LoginView, LogoutView, ProfileUpdateView, ProfileView,
                    UsersView, SendFriendRequestView, MyNetworksView, AcceptFriendRequestView, ResetPasswordView,
                    IgnoreFriendRequestView, DeleteFromFriendsView)

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('profile/', ProfileUpdateView.as_view(), name="profile"),
    path('profile_view/', ProfileView.as_view(), name="profile_view"),
    path('list/', UsersView.as_view(), name="list"),
    path('reset-password/', ResetPasswordView.as_view(), name="reset_password"),



    #users friend request logic
    path('send_request/<int:id>/', SendFriendRequestView.as_view(), name="send_request"),
    path('networks/', MyNetworksView.as_view(), name="my_networks"),
    path('accept-friend/<int:id>/', AcceptFriendRequestView.as_view(), name="accept_friend"),
    path('ignore-friend/<int:id>/', IgnoreFriendRequestView.as_view(), name="ignore_friend"),
    path('delete-friend/<int:id>/', DeleteFromFriendsView.as_view(), name="delete_friend"),
]

templates/base.html
<!doctype html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <title>{% block title %} Places project {% endblock %}</title>
</head>
<body class="px-5">

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'landing_page' %}">Landing Page</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>

            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'places:list' %}">Places</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'users:list' %}">Users</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'users:my_networks' %}">My Networks</a>
            </li>


          </ul>
            <ul class="navbar-nav me-5 mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          {{ user.username }}
                      </a>
                      <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'users:profile_view' %}">Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                      </ul>
                    </li>
                {% else %}
                    <a href="{% url 'users:login' %}" class="btn btn-outline-primary">Log in </a>
                {% endif %} 

            
            </ul>

{#          <form class="d-flex" role="search">#}
{#            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">#}
{#            <button class="btn btn-outline-success" type="submit">Search</button>#}
{#          </form>#}
        </div>
      </div>
    </nav>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
              {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    
    {% block content %}

    {% endblock %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% load static %}
{% block title %} Places Page {% endblock title %}
{% block content %}
<div class="container posts-content" style="margin-top:20px;">
  <div class="row justify-content-center"> <!-- Centering the content horizontally -->
    <div class="col-lg-6">
        {% for review in place_reviews %}
        	<div class="card mb-4" style="border: 1px solid rgba(24,28,33,0.06);">
        <div class="card-body">
          <div class="media mb-3">
            <img src="{{ review.user.photo.url }}" class="d-block ui-w-40 rounded-circle" alt="" style="width: 40px; height: auto;">
            <div class="media-body ml-3">
              <i><b>{{ review.user.username }}</b></i> rated it <b>{{ review.stars_given }}</b> stars
              <div class="text-muted small">{{ review.created_at }}</div>
            </div>
          </div>
          <p>
            {{ review.comment_text }}
          </p>
          <a href="javascript:void(0)" class="ui-rect ui-bg-cover" style="background-color: transparent; background-position: center center; background-size: cover; display: block; width: 100%; position: relative;">
            <img src="{{ review.place.image.url }}" class="ui-rect-content" alt="" width="100%" height="400px">
          </a>
        </div>
        <div class="card-footer" style="border-color: rgba(24,28,33,0.06);">
          <a href="javascript:void(0)" class="d-inline-block text-muted">
            <strong>123</strong> <small class="align-middle">Likes</small>
          </a>
          <a href="javascript:void(0)" class="d-inline-block text-muted ml-3">
            <strong>12</strong> <small class="align-middle">Comments</small>
          </a>
          <a href="javascript:void(0)" class="d-inline-block text-muted ml-3">
            <small class="align-middle">Repost</small>
          </a>
        </div>
      </div>
        {% endfor %}


    </div>
  </div>
</div>

{% endblock content %}

templates/landing.html
{% extends 'base.html' %}

{% block title %}
	Landing Page

{% endblock %}



{% block content %}

    <h1>Landing Page</h1>

    {% if messages %}
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    {% endif %}

    <p>
        <a href="{% url 'users:register' %}">Register</a>  /
        {% if user.is_authenticated %}
            <a href="{% url 'users:logout' %}">Logout</a> /
        {% else %}
            <a href="{% url 'users:login' %}">Login</a> /
        {% endif %}

        <a href="{% url 'places:list' %}">Places</a> /
        <a href="{% url 'users:profile' %}">Profile</a>
    </p>

{% endblock %}